spring:
  # 应用名(个人习惯配置上)
  application:
    name: security-example
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  session:
    # 暂时关闭spring session
    store-type: none
security:
  basic:
    # 关闭默认配置
    enabled: false